#include "DNS_flag.h"

QR_CONSTANTS.QUERY    			= 0;
QR_CONSTANTS.RESPONSE 			= 1;

OPCODE_CONSTANTS.QUERY  		= 0;
OPCODE_CONSTANTS.IQUERY 		= 1;
OPCODE_CONSTANTS.STATUS 		= 2;

AA_CONSTANTS.QUERY_NAME      	= 0;
AA_CONSTANTS.ANSWER_NAME     	= 1;

TC_CONSTANTS.NOT_TRUNCATED   	= 0;
TC_CONSTANTS.TRUNCATED       	= 1;

RD_CONSTANTS.REC_UNDESIRED   	= 0;
RD_CONSTANTS.REC_DESIRED     	= 1;

RA_CONSTANTS.REC_UNAVAILABLE 	= 0;
RA_CONSTANTS.REC_AVAILABLE   	= 1;

RCODE_CONSTANTS.NO_ERROR        = 0;
RCODE_CONSTANTS.FORMAT_ERROR    = 1;
RCODE_CONSTANTS.SERVER_FAILURE  = 2;
RCODE_CONSTANTS.NAME_ERROR      = 3;
RCODE_CONSTANTS.NOT_IMPLEMENTED = 4;
RCODE_CONSTANTS.REFUSED         = 5;

QTYPE_CONSTANTS.A      			= 1;
QTYPE_CONSTANTS.NS     			= 2;
QTYPE_CONSTANTS.MD     			= 3;
QTYPE_CONSTANTS.MF     			= 4;
QTYPE_CONSTANTS.CNAME  			= 5;
QTYPE_CONSTANTS.SOA    			= 6;
QTYPE_CONSTANTS.MB     			= 7;
QTYPE_CONSTANTS.MG     			= 8;
QTYPE_CONSTANTS.MR     			= 9;
QTYPE_CONSTANTS.NULLRR 			= 10;
QTYPE_CONSTANTS.WKS    			= 11;
QTYPE_CONSTANTS.PTR    			= 12;
QTYPE_CONSTANTS.HINFO  			= 13;
QTYPE_CONSTANTS.MINFO  			= 14;
QTYPE_CONSTANTS.MX     			= 15;
QTYPE_CONSTANTS.TXT    			= 16;
QTYPE_CONSTANTS.AXFR   			= 252;
QTYPE_CONSTANTS.MAILB  			= 253;
QTYPE_CONSTANTS.MAILA  			= 254;
QTYPE_CONSTANTS.ALL    			= 255;

CLASS_CONSTANTS.IN     			= 1;
CLASS_CONSTANTS.CS     			= 2;
CLASS_CONSTANTS.CH     			= 3;
CLASS_CONSTANTS.HS     			= 4;
CLASS_CONSTANTS.ALL    			= 255;